"""musor_ls str

Revision ID: 3610fcb3cc1a
Revises: 54491e3d1ca2
Create Date: 2023-03-02 10:33:10.863855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3610fcb3cc1a'
down_revision = '54491e3d1ca2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
