"""addr cascade del

Revision ID: 4a09f234cdb9
Revises: b66407b36281
Create Date: 2023-03-02 11:23:21.090219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a09f234cdb9'
down_revision = 'b66407b36281'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('propiska_address_id_fkey', 'propiska', type_='foreignkey')
    op.create_foreign_key(None, 'propiska', 'address', ['address_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'propiska', type_='foreignkey')
    op.create_foreign_key('propiska_address_id_fkey', 'propiska', 'address', ['address_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
