"""user fio added

Revision ID: 59aeba7edc8c
Revises: 20789bbef9a4
Create Date: 2023-03-01 22:12:03.022292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59aeba7edc8c'
down_revision = '20789bbef9a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fio', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fio')
    # ### end Alembic commands ###
