"""blacklist

Revision ID: 6423541f87f8
Revises: 63dbe6581e4e
Create Date: 2023-10-18 00:24:34.613003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6423541f87f8'
down_revision = '63dbe6581e4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist')
    # ### end Alembic commands ###
