"""Phone column corrected

Revision ID: 77957c563621
Revises: 94eab2d901cf
Create Date: 2023-02-27 14:59:06.824817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77957c563621'
down_revision = '94eab2d901cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phones', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('phones', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('phones_user_id_fkey', 'phones', type_='foreignkey')
    op.create_foreign_key(None, 'phones', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phones', type_='foreignkey')
    op.create_foreign_key('phones_user_id_fkey', 'phones', 'users', ['user_id'], ['id'])
    op.alter_column('phones', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('phones', 'created_at')
    # ### end Alembic commands ###
