"""address expanded

Revision ID: 7f36a994e9ba
Revises: aea161c40268
Create Date: 2023-03-01 17:45:55.831127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f36a994e9ba'
down_revision = 'aea161c40268'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('gaz_litsevoy_schet', sa.Integer(), nullable=False))
    op.add_column('address', sa.Column('owner_fio', sa.String(length=100), nullable=False))
    op.add_column('address', sa.Column('owner_tel', sa.String(length=20), nullable=False))
    op.add_column('address', sa.Column('room_size', sa.String(length=20), nullable=False))
    op.add_column('address', sa.Column('kadastr_number', sa.String(length=30), nullable=False))
    op.add_column('address', sa.Column('gaz_schetchik_nomer', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'gaz_schetchik_nomer')
    op.drop_column('address', 'kadastr_number')
    op.drop_column('address', 'room_size')
    op.drop_column('address', 'owner_tel')
    op.drop_column('address', 'owner_fio')
    op.drop_column('address', 'gaz_litsevoy_schet')
    # ### end Alembic commands ###
