"""Added rel

Revision ID: 94eab2d901cf
Revises: 059bf6edafb6
Create Date: 2023-02-27 13:57:26.982817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94eab2d901cf'
down_revision = '059bf6edafb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phones', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'phones', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phones', type_='foreignkey')
    op.drop_column('phones', 'user_id')
    # ### end Alembic commands ###
