"""propiska uniq

Revision ID: aea161c40268
Revises: abaf9b49cb60
Create Date: 2023-03-01 14:24:27.032889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea161c40268'
down_revision = 'abaf9b49cb60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'propiska', ['user_id', 'address_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'propiska', type_='unique')
    # ### end Alembic commands ###
