"""init

Revision ID: d3960092f4ed
Revises: 
Create Date: 2023-02-26 20:45:27.822007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3960092f4ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('fio', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('house_number', sa.Integer(), nullable=True),
    sa.Column('apartment_number', sa.Integer(), nullable=True),
    sa.Column('awaiting_register', sa.Boolean(), nullable=True),
    sa.Column('isRegistered', sa.Boolean(), nullable=True),
    sa.Column('canRegisterUser', sa.Boolean(), nullable=True),
    sa.Column('whoRegistered', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
