"""domkoms info

Revision ID: e1a97ce79f3e
Revises: fe19230fce36
Create Date: 2023-02-28 12:29:48.631800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a97ce79f3e'
down_revision = 'fe19230fce36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domkoms', sa.Column('telegram_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domkoms', 'telegram_id')
    # ### end Alembic commands ###
